# Generated by Django 3.2.10 on 2021-12-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specs',
            old_name='Value',
            new_name='value',
        ),
    ]
