# Generated by Django 3.2.10 on 2021-12-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_rename_value_specs_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(default='x', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='image',
            field=models.ImageField(default='z', upload_to=''),
            preserve_default=False,
        ),
    ]
