# Generated by Django 3.2.10 on 2021-12-10 23:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_auto_20211210_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=tinymce.models.HTMLField(default='<br>'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='description',
            field=tinymce.models.HTMLField(default='<br>'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
