# Generated by Django 3.2.10 on 2022-01-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_auto_20211211_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
