# Generated by Django 3.2.10 on 2022-01-30 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_auto_20220125_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='rate',
            field=models.SmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
